- hosts: aws
  vars_files: creds.yaml
  tasks:
  - name: Install httpd Software
    package:
      name: "httpd"
      state: present
  - name : Copy web page
    copy:
      dest: "/var/www/html"
      src: "/var/lib/jenkins/workspace/webproject/index.html"
       
  - name: Start the server
    service:
      name: "httpd"
      state: started
      enabled: yes

  - name: Sending Mail to the developer when website is updated
    mail:
      host: smtp.gmail.com
      port: 587
      secure: starttls
      username: tinkalshakya8650@gmail.com
      password: "{{ pass }}"
      to: "tinkalshakya283125@gmail.com"
      subject: "webpage update"
      body: "Your server webpage is updated."
