- hosts: aws
  vars_files:
  - creds.yaml
  tasks:
  - name: Install httpd Software
    package:
      name: "httpd"
      state: present
  - name : Copy web page
    copy:
      dest: "/var/www/html"
      src: "/var/lib/jenkins/workspace/webproject/index.html"
       
  - name: Start the server
    service:
      name: "httpd"
      state: started
      enabled: yes

  - name: Sending Mail to the developer when website is updated
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ user }}"
      password: "{{ pass }}"
      to: tinkalshakya283125@gmail.com
      subject: webpage update
      body: Your {{ ansible_hostname }} server webpage is updated.

