- hosts: web
  tasks:
  - name: Install httpd Software
    package:
      name: "httpd"
      state: present
  - name : Copy web page
    copy:
      dest: "/var/www/html"
      src: "/var/lib/jenkins/workspace/webproject/index.html"
       
  - name: Start the server
    service:
      name: "httpd"
      state: started
      enabled: yes

